### ISSUE TITLE
Clocks for both sides count down for the first move of a new game

### ISSUE THREAD

**Issue by HansOveL** [scs-ben/tcec-gui#117] opened 2018-09-26 22:30 UTC
When a new game is started, for the the very first move, the clocks for both white and black count down.

If we refresh it fixes itself. When the first move has been played it fixes itself.

**Comment by arunsathya1309** [comment] 2018-09-27 16:51
I believe its fixed

**Comment by arunsathya1309** [comment] 2018-09-27 23:12
its not fixed

**Comment by arunsathya1309** [comment] 2018-09-28 05:40
This issues seems to be solved after latest fix

**Comment by kanchess** [comment] 2018-09-28 19:42
FYI the issue is not yet fixed imo, it unfortunately persists. i perceive it both in chrome and firefox...
and i observed this certainly restarting everything hours after your last remark, so i am confident i did not fail to refresh in this case.
thank you in advance for looking at it again arun!

**Comment by arunsathya1309** [comment] 2018-09-28 23:15
this is a tricky one to fix, as it happens after the first move of new game, im looking into it

**Comment by kanchess** [comment] 2018-09-29 23:49
it seems fixed now, ty so much arun!

**Comment by arunsathya1309** [comment] 2018-09-30 00:49
Lets hope so :) there are so many variants

**Comment by arunsathya1309** [comment] 2018-09-30 00:50
Closed by mistake, let it be open for few days

**Comment by arunsathya1309** [comment] 2018-10-01 19:47
fixed

**Closed by arunsathya1309** 2018-10-01 19:47 UTC
